### ISSUE TITLE
Config for secrets

### ISSUE THREAD

**Issue by Joed11** [HRNYC-Taiyaki/product-service#1]
https://github.com/HRNYC-Taiyaki/product-service/blob/c6e312d280ff9f04f1d68dda811e1b88e0262796/db/index.ts#L2

Nice job using a config file.  That said it appears your config file got uploaded to GitHub at some point.  Hide that file and find ways to inject environment variables from the environments the program will run in.

**Comment by dd0sxx** [comment]
Thanks, fixed this and removed the config and node modules from the repo
